language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install numpy docopt"
# command to run tests
script: 
  - ./tzwhere/tzwhere.py -k csv test
  - ./tzwhere/tzwhere.py -k json test
  - ./tzwhere/tzwhere.py -k pickle test
